version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  web:
    build: .
    command: bash -c "cd /app && PYTHONPATH=/app uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default
    
  celery_worker:
    build: .
    command: bash -c "cd /app && PYTHONPATH=/app celery -A src.celery:app worker --loglevel=info"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    depends_on:
      - redis
      - web
    env_file:
      - .env
    working_dir: /app
  
volumes:
  postgres_data:
